export const ExperimentsObject = {
    "Code Pen": [
        {
            id:1,
            category:'js',
            desc:'A pen to demonstrate how to make parallel API calls with Promises',
            title: 'Parallel Calls with Promise',
            imgSrc:'',
            link:'https://codepen.io/Rajdeepc/pen/gOpqmmd',
            author:'Rajdeep Chandra',
        },
        {
            id:2,
            category:'app',
            desc:'A simple todo app to do add,delete and retain your list via LocalStorage',
            title: 'React Todo List with count',
            imgSrc:'',
            link:'https://codepen.io/Rajdeepc/pen/MWWKVQE',
            author:'Rajdeep Chandra',
        },
        {
            id:3,
            category:'js',
            desc:'Login and Logout functionality with React, Retain Session on login and destroy sessions on Logout',
            title: 'Login and Logout with React',
            imgSrc:'https://codepen.io/Rajdeepc/embed/preview/PawvmN?height=265&theme-id=dark&default-tab=js,result',
            link:'https://codepen.io/Rajdeepc/pen/PawvmN',
            author:'Rajdeep Chandra',
        },
        {
            id:4,
            category:'js',
            desc:'Stack of cards project with plain JS.',
            title: 'Material Card Stack with Vanilla JS',
            imgSrc:'https://codepen.io/Rajdeepc/embed/preview/MmPRpE?height=265&theme-id=dark&default-tab=css,result',
            link:'https://codepen.io/Rajdeepc/pen/MmPRpE',
            author:'Rajdeep Chandra',
        },
        {
            id:5,
            category:'code',
            desc:'A simple pen to show how to add multiple items into SessionStorage and get items from the storage',
            title: 'HTML5 SessionStorage API',
            imgSrc:'https://codepen.io/Rajdeepc/embed/preview/vKEvrr?height=265&theme-id=dark&default-tab=js,result',
            link:'https://codepen.io/Rajdeepc/pen/vKEvrr',
            author:'Rajdeep Chandra',
        }
    ],
    "Open Source Projects":[
        {
            id:1,
            category:'project',
            desc:'A demo on how to create a Ceaser Cipher with JavaScript',
            title: 'Ceaser Cipher wtih JS ',
            imgSrc:'',
            link:'https://jsfiddle.net/rajrock38/05qw3cny/',
            author:'Rajdeep Chandra',
        },
        {
            id:2,
            category:'project',
            desc:'A polyfill fallback method for bind() to support legacy browsers',
            title: 'Polyfill for bind method',
            imgSrc:'',
            link:'https://jsfiddle.net/rajrock38/3h02n5sy/',
            author:'Rajdeep Chandra',
        },
        {
            id:3,
            category:'code',
            desc:'How to check your network bandwidth with JavaScript',
            title: 'Network Bandwidth Checker',
            imgSrc:'',
            link:'https://jsfiddle.net/rajrock38/etp8ycx7/',
            author:'Rajdeep Chandra',
        },
        {
            id:4,
            category:'js',
            desc:'A configurable animated clock which works based on your current time zone.',
            title: 'Animated Clock',
            imgSrc:'',
            link:'https://jsfiddle.net/rajrock38/etp8ycx7/',
            author:'Rajdeep Chandra',
        },
        {
            id:5,
            category:'project',
            desc:'A url shortener app, where you can shorten urls, save ur urls for future use like bitly.com',
            title: 'URL Shortener',
            imgSrc:'',
            link:'https://razorurl.herokuapp.com/',
            author:'Rajdeep Chandra',
        }
    ]
}